package com.java;
import java.util.Random;
import java.util.Scanner;


/*
The fun and easy project "Guess the number" is a short Java project that allows the user to guess the number generated by the computer and involve the following steps:
1.The system generates a random number from a given range, say 1 to 100.
2.The user is prompted to enter their given number in a displayed dialogue box.
3.The computer then tells if the entered number matches the guesses number or it is higher/lower than the generated number.
4. The game continues under the user guessing the number.

You can also incorporate further details as:
Limiting the number of attempts.
Adding more rounds.
Displaying score.
Giving points based on the number of attempts
 */
public class GuessTheNumber {
    public static void main(String[] args) {
        Scanner scan=new Scanner(System.in);//for getting input from user
        int score = 0; // user's score
        Random rand = new Random(); // random number generator
        int guess; // user's guess
        int target; // computer-generated number
        int round=0;
       while (true){
               target = rand.nextInt(100) + 1; // generate random number
               System.out.println("Round " + ++round + ": Guess the number between 1 and " + 100 + ".");
               for (int j = 1; j <= 10; j++) {
                   System.out.println("Guess # "+j+": ");
                   guess=scan.nextInt();
                   // check if guess matches target
                   if (guess == target) {
                       System.out.println("Congratulations, you guessed the number in " + j + " attempts!");
                       score += (11 - j ); // add score based on number of attempts
                       break; // end current round
                   } else if (guess < target) System.out.println("Too low, try again.");
                   else System.out.println("Too high, try again.");
                   // if max attempts reached and user has not guessed correctly, end round
                   if (j == 10) System.out.println("Sorry, you have run out of attempts. The number was " + target + ".");

               }
               System.out.println("Would you like to continue? (1/0):");
               if(scan.nextInt()==0)break;
       }


        System.out.println("Your final score is " + score + ".");
    }
}

